### ISSUE TITLE
Getting backup IDs

### ISSUE THREAD

**Issue by brandonhilkert** [jurriaan/Ruby-iCloud#7]
I poked around the code and am able to call to get the backup devices, and then call for backups on a particular `udid`. However, I don't see a `backup_id` (ref: https://github.com/jurriaan/Ruby-iCloud/blob/master/lib/ruby-icloud/requests/Backup/backupfilesrequest.rb#L3). 

```
#<RubyiCloud::ProtocolBuffers::Backup index=1 size=989632529 timestamp=2015-08-30 21:35:54 -0400 device_info=#<RubyiCloud::ProtocolBuffers::DeviceInfo name="x's iPad" version="8.3" build="12F69" unknown1=2 unknown="2451e46db4bc4055bf126c8b26b15800" unknown2=2 unknown3=1> timestamp2=2015-07-11 21:22:31 -0400>
```
Is there an easy way to get this backup ID?

**Comment by brandonhilkert** [comment]
My bad, looks like it's the index. Closing.

**Comment by jurriaan** [comment]
I'm actually amazed this thing still works! Hopefully its useful to you
