### ISSUE TITLE
Downloading files

### ISSUE THREAD

**Issue by brandonhilkert** [jurriaan/Ruby-iCloud#8]
Any chance you could offer some guidance on downloading files. I was able to get the hash and auth token from an individual file list. I can show you what I have so far if it helps. I tried to follow the other issue about backups, but I'm afraid it's slightly beyond my knowledge level ;)

**Comment by jurriaan** [comment]
Unfortunately I never got that part working :( and don't really have the time to look into it at the moment.

**Comment by brandonhilkert** [comment]
Any interest in being paid for it?
